export const GNUCASH_ACCOUNTS = [
  "ASSET",
  "ASSET:Assets",
  "ASSET:Assets:Current Assets",
  "ASSET:Assets:Current Assets:Cash in Hand",
  "ASSET:Assets:Current Assets:Cash in Hand:Backend",
  "ASSET:Assets:Current Assets:Cash in Hand:Wallet",
  "ASSET:Assets:Current Assets:Foriegn Exchange",
  "ASSET:Assets:Current Assets:Checking Account",
  "ASSET:Assets:Current Assets:Savings Account",
  "ASSET:Assets:Current Assets:Savings Account:Andra Bank",
  "ASSET:Assets:Current Assets:Savings Account:Axis Bank",
  "ASSET:Assets:Current Assets:Savings Account:HDFC Bank",
  "ASSET:Assets:Current Assets:Savings Account:Indian Bank",
  "ASSET:Assets:Current Assets:Savings Account:Pay Wallets",
  "ASSET:Assets:Current Assets:Savings Account:Pay Wallets:Amazon Pay Balance",
  "ASSET:Assets:Current Assets:Savings Account:Pay Wallets:Freecharge",
  "ASSET:Assets:Current Assets:Savings Account:SBI Current Acount",
  "ASSET:Assets:Current Assets:Savings Account:SBI Joint Account",
  "ASSET:Assets:Current Assets:Savings Account:IDFC Bank",
  "ASSET:Assets:Loan",
  "LIABILITY",
  "LIABILITY:Liabilities",
  "LIABILITY:Liabilities:Credit Card",
  "LIABILITY:Liabilities:Credit Card:IDFC Credit Card",
  "LIABILITY:Liabilities:Credit Card:SBI Credit Card",
  "LIABILITY:Liabilities:Aarco",
  "LIABILITY:Liabilities:Dad Loan for Business",
  "LIABILITY:Liabilities:Loans Given",
  "LIABILITY:Liabilities:Others Money",
  "LIABILITY:Liabilities:Pending amounts",
  "LIABILITY:Liabilities:Phone",
  "INCOME",
  "INCOME:Income",
  "INCOME:Income:Bonus",
  "INCOME:Income:Cashback",
  "INCOME:Income:Consulting",
  "INCOME:Income:Dad money",
  "INCOME:Income:Dividend",
  "INCOME:Income:Gambling casino",
  "INCOME:Income:Gifts Received",
  "INCOME:Income:Interest Income",
  "INCOME:Income:Interest Income:Checking Interest",
  "INCOME:Income:Interest Income:Other Interest",
  "INCOME:Income:Interest Income:Savings Interest",
  "INCOME:Income:Other Income",
  "INCOME:Income:Other Income:Reimbursement",
  "INCOME:Income:Other Income:Tax reimbursement",
  "INCOME:Income:Salary",
  "INCOME:Income:Salary:1 Psychology in Tamil Entity",
  "INCOME:Income:Salary:1 Psychology in Tamil Entity:Website Business",
  "INCOME:Income:Salary:Element H",
  "INCOME:Income:Salary:Foriegn exchange",
  "INCOME:Income:Salary:Foriegn exchange:Dubai",
  "INCOME:Income:Salary:Gahan Movie",
  "INCOME:Income:Salary:Google Payments",
  "INCOME:Income:Salary:HIMT",
  "INCOME:Income:Salary:Mcgans Ooty",
  "INCOME:Income:Salary:Music",
  "INCOME:Income:Salary:Online Business",
  "INCOME:Income:Salary:Online Business:Amazon Affiliate",
  "INCOME:Income:Salary:Online Business:Amazon KDP",
  "INCOME:Income:Salary:Online Business:Amazon Seller Central",
  "INCOME:Income:Salary:Online Business:Fiverr Online",
  "INCOME:Income:Salary:Online Business:Private Consulting",
  "INCOME:Income:Salary:Online Business:Workshops",
  "INCOME:Income:Salary:Online Business:Workshops:Assertive Communication",
  "INCOME:Income:Salary:Online Business:Workshops:Basic Psy oc15 17 Workshop",
  "INCOME:Income:Salary:Online Business:Workshops:Consolidated Website Earnings",
  "INCOME:Income:Salary:Online Business:Workshops:digital marketing 2020",
  "INCOME:Income:Salary:Online Business:Workshops:EQ Workshop",
  "INCOME:Income:Salary:Online Business:Workshops:Leadership 4 feb 18",
  "INCOME:Income:Salary:Online Business:Workshops:Leadership Workshop 26 Nov17",
  "INCOME:Income:Salary:Online Business:Workshops:MBA Workshop",
  "INCOME:Income:Salary:Online Business:Workshops:money and life management 2021",
  "INCOME:Income:Salary:Online Business:Workshops:Money manag coim 1012",
  "INCOME:Income:Salary:Online Business:Workshops:Money Management Jan28 2018",
  "INCOME:Income:Salary:Online Business:Workshops:Money Management Workshop 5 no 17",
  "INCOME:Income:Salary:Online Business:Workshops:Pre Marital 2018",
  "INCOME:Income:Salary:Online Business:Workshops:SIS Dubey",
  "INCOME:Income:Salary:Online Business:Workshops:TDP Jan 567 2018",
  "INCOME:Income:Salary:Online Business:Youtube",
  "INCOME:Income:Salary:Other Education",
  "INCOME:Income:Salary:Pearl",
  "INCOME:Income:Salary:Scale Up Training",
  "INCOME:Income:Salary:St Thomas",
  "INCOME:Income:Salary:Sun TV",
  "INCOME:Income:Salary:Web Development",
  "INCOME:Income:Salary:Win or Win",
  "INCOME:Income:Salary:YES Chamber of commerce",
  "INCOME:Income:Selling Stuff",
  "EXPENSE",
  "EXPENSE:Expenses",
  "EXPENSE:Expenses:1 Material",
  "EXPENSE:Expenses:1 Material:Prec Metals",
  "EXPENSE:Expenses:1 Material:Repair",
  "EXPENSE:Expenses:1 Material:Software",
  "EXPENSE:Expenses:1 Material:Books",
  "EXPENSE:Expenses:1 Material:Computer",
  "EXPENSE:Expenses:1 Material:Electronics",
  "EXPENSE:Expenses:1 Material:Equipment",
  "EXPENSE:Expenses:2 Food",
  "EXPENSE:Expenses:2 Food:Dining",
  "EXPENSE:Expenses:2 Food:Snaks",
  "EXPENSE:Expenses:2 Food:Takeout/Delivery",
  "EXPENSE:Expenses:3 Website Business",
  "EXPENSE:Expenses:3 Website Business:AARCO Joint Venture",
  "EXPENSE:Expenses:3 Website Business:Ads",
  "EXPENSE:Expenses:3 Website Business:Education Activities",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Bills",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Equipement",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Hotels Rooms",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Incidentals",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Interest for Loan",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:miscellaneous business expense",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Salary",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:sundry salary",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Travel expenses",
  "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Website",
  "EXPENSE:Expenses:3 Website Business:Psyasap",
  "EXPENSE:Expenses:3 Website Business:Psychologyintamil",
  "EXPENSE:Expenses:3 Website Business:Salary for Works",
  "EXPENSE:Expenses:3 Website Business:V S Jithendra Personal Site",
  "EXPENSE:Expenses:3 Website Business:Workshops",
  "EXPENSE:Expenses:3 Website Business:Workshops:2022 April Workshop",
  "EXPENSE:Expenses:3 Website Business:Workshops:2022 May Workshop",
  "EXPENSE:Expenses:3 Website Business:Workshops:Assertive Com Workshop",
  "EXPENSE:Expenses:3 Website Business:Workshops:Basic Psy oc 17 Workshop",
  "EXPENSE:Expenses:3 Website Business:Workshops:Business Strategy Workshop Aug2018",
  "EXPENSE:Expenses:3 Website Business:Workshops:critical thinking 2022",
  "EXPENSE:Expenses:3 Website Business:Workshops:digital maketing 2020",
  "EXPENSE:Expenses:3 Website Business:Workshops:EQ Workshop",
  "EXPENSE:Expenses:3 Website Business:Workshops:Leadership 26 Nov",
  "EXPENSE:Expenses:3 Website Business:Workshops:Leadership 4 feb 18",
  "EXPENSE:Expenses:3 Website Business:Workshops:Leadership fr SMall Business Trichy",
  "EXPENSE:Expenses:3 Website Business:Workshops:MBA Workshop 2025",
  "EXPENSE:Expenses:3 Website Business:Workshops:MM3 Jan 28 18",
  "EXPENSE:Expenses:3 Website Business:Workshops:money and life management 2021",
  "EXPENSE:Expenses:3 Website Business:Workshops:Money Management Dec10",
  "EXPENSE:Expenses:3 Website Business:Workshops:Money Management No 17",
  "EXPENSE:Expenses:3 Website Business:Workshops:Pre Marital Workshop 2018",
  "EXPENSE:Expenses:3 Website Business:Workshops:Relationship 24",
  "EXPENSE:Expenses:3 Website Business:Workshops:SIS Feb 28",
  "EXPENSE:Expenses:3 Website Business:Workshops:Trainer Development",
  "EXPENSE:Expenses:3 Website Business:Workshops:Workshops Consolidated 2019",
  "EXPENSE:Expenses:3 Website Business:Youtube Materials",
  "EXPENSE:Expenses:4 Music Business Expenses",
  "EXPENSE:Expenses:4 Music Business Expenses:Ads",
  "EXPENSE:Expenses:4 Music Business Expenses:Education",
  "EXPENSE:Expenses:4 Music Business Expenses:Gahan Music Expenses",
  "EXPENSE:Expenses:4 Music Business Expenses:INstrument and Others",
  "EXPENSE:Expenses:4 Music Business Expenses:own compose songs",
  "EXPENSE:Expenses:4 Music Business Expenses:Software",
  "EXPENSE:Expenses:4 Music Business Expenses:Video Shoot Expenses",
  "EXPENSE:Expenses:5 Amazon Business",
  "EXPENSE:Expenses:5 Amazon Business:Books",
  "EXPENSE:Expenses:5 Amazon Business:Equipments",
  "EXPENSE:Expenses:5 Amazon Business:Other Tools",
  "EXPENSE:Expenses:5 Amazon Business:Stationary",
  "EXPENSE:Expenses:6 Foriegn Expenses",
  "EXPENSE:Expenses:6 Foriegn Expenses:Dubai",
  "EXPENSE:Expenses:7 Indpendent Consulting",
  "EXPENSE:Expenses:7 Indpendent Consulting:Cabs and Others",
  "EXPENSE:Expenses:7 Indpendent Consulting:Food",
  "EXPENSE:Expenses:7 Indpendent Consulting:Tickets for Travels",
  "EXPENSE:Expenses:Adjustment",
  "EXPENSE:Expenses:Advertisement",
  "EXPENSE:Expenses:Auto",
  "EXPENSE:Expenses:Auto:Bus",
  "EXPENSE:Expenses:Auto:Cab",
  "EXPENSE:Expenses:Auto:Car",
  "EXPENSE:Expenses:Auto:Fees",
  "EXPENSE:Expenses:Auto:Gas",
  "EXPENSE:Expenses:Auto:Parking",
  "EXPENSE:Expenses:Auto:Repair and Maintenance",
  "EXPENSE:Expenses:Bank Service Charge",
  "EXPENSE:Expenses:Domestic",
  "EXPENSE:Expenses:Domestic :apartment maintenance",
  "EXPENSE:Expenses:Domestic :Appliances",
  "EXPENSE:Expenses:Domestic :Borewell",
  "EXPENSE:Expenses:Domestic :House expense",
  "EXPENSE:Expenses:Domestic :Household Items",
  "EXPENSE:Expenses:Domestic :Maintanance",
  "EXPENSE:Expenses:Durga Marriage",
  "EXPENSE:Expenses:Education",
  "EXPENSE:Expenses:Education:Books",
  "EXPENSE:Expenses:Education:Fees",
  "EXPENSE:Expenses:Education:Online Courses",
  "EXPENSE:Expenses:Education:PHD",
  "EXPENSE:Expenses:Entertainment",
  "EXPENSE:Expenses:Entertainment:Games",
  "EXPENSE:Expenses:Entertainment:Music/Movies",
  "EXPENSE:Expenses:Entertainment:Recreation",
  "EXPENSE:Expenses:Entertainment:Subscription",
  "EXPENSE:Expenses:Entertainment:Travel",
  "EXPENSE:Expenses:Fine",
  "EXPENSE:Expenses:Gifts",
  "EXPENSE:Expenses:Govt",
  "EXPENSE:Expenses:Groceries",
  "EXPENSE:Expenses:Hobbies",
  "EXPENSE:Expenses:Insurance",
  "EXPENSE:Expenses:Insurance:Auto Insurance",
  "EXPENSE:Expenses:Insurance:Health Insurance",
  "EXPENSE:Expenses:Insurance:Life Insurance",
  "EXPENSE:Expenses:Laundry/Dry Cleaning",
  "EXPENSE:Expenses:Lifestyle",
  "EXPENSE:Expenses:Lifestyle:Clothes",
  "EXPENSE:Expenses:Lifestyle:Other",
  "EXPENSE:Expenses:Marriage",
  "EXPENSE:Expenses:Medical Expenses",
  "EXPENSE:Expenses:Miscellaneous",
  "EXPENSE:Expenses:office",
  "EXPENSE:Expenses:Online Services",
  "EXPENSE:Expenses:Phone",
  "EXPENSE:Expenses:Public Transportation",
  "EXPENSE:Expenses:Rent",
  "EXPENSE:Expenses:Salary",
  "EXPENSE:Expenses:Spent for Others in Debt",
  "EXPENSE:Expenses:Stationary",
  "EXPENSE:Expenses:Subscriptions",
  "EXPENSE:Expenses:Subscriptions:Other Media",
  "EXPENSE:Expenses:Subscriptions:SBI Credit Card",
  "EXPENSE:Expenses:Supplies",
  "EXPENSE:Expenses:Taxes",
  "EXPENSE:Expenses:Taxes:Auditor Fees",
  "EXPENSE:Expenses:Taxes:Federal",
  "EXPENSE:Expenses:Taxes:income Tax",
  "EXPENSE:Expenses:Taxes:Medicare",
  "EXPENSE:Expenses:Taxes:Other Tax",
  "EXPENSE:Expenses:Taxes:Social Security",
  "EXPENSE:Expenses:Taxes:State/Province",
  "EXPENSE:Expenses:Utilities",
  "EXPENSE:Expenses:Utilities:Electric",
  "EXPENSE:Expenses:Utilities:Garbage collection",
  "EXPENSE:Expenses:Utilities:Gas",
  "EXPENSE:Expenses:Utilities:Water",
  "EXPENSE:Expenses:Vacation",
  "EXPENSE:Expenses:Vacation:andaman 2019",
  "EXPENSE:Expenses:Vacation:Banglore",
  "EXPENSE:Expenses:Vacation:Banglore 2017",
  "EXPENSE:Expenses:Vacation:banglore 2019",
  "EXPENSE:Expenses:Vacation:bombay",
  "EXPENSE:Expenses:Vacation:China 2025",
  "EXPENSE:Expenses:Vacation:Coimbatore Nov2017",
  "EXPENSE:Expenses:Vacation:Coonor jEYKAR WEDDING",
  "EXPENSE:Expenses:Vacation:Coorg 2017 Dec",
  "EXPENSE:Expenses:Vacation:Coorg 2022",
  "EXPENSE:Expenses:Vacation:Coorg with Jey friends",
  "EXPENSE:Expenses:Vacation:delhi manali 2019-20",
  "EXPENSE:Expenses:Vacation:Dubai 2022",
  "EXPENSE:Expenses:Vacation:Goa 2017",
  "EXPENSE:Expenses:Vacation:Goa 2018",
  "EXPENSE:Expenses:Vacation:Goa 2019 July",
  "EXPENSE:Expenses:Vacation:Goa 2019 March",
  "EXPENSE:Expenses:Vacation:Goa 2021",
  "EXPENSE:Expenses:Vacation:Goa 2022",
  "EXPENSE:Expenses:Vacation:Goa 2024",
  "EXPENSE:Expenses:Vacation:Goa may 2021",
  "EXPENSE:Expenses:Vacation:GOA TRIP",
  "EXPENSE:Expenses:Vacation:Goa Trip 2016 May",
  "EXPENSE:Expenses:Vacation:Honeymoon",
  "EXPENSE:Expenses:Vacation:Jeshu wedding",
  "EXPENSE:Expenses:Vacation:Kanyakumari Trip",
  "EXPENSE:Expenses:Vacation:Kishore wedding",
  "EXPENSE:Expenses:Vacation:Leh 23",
  "EXPENSE:Expenses:Vacation:Mahabalipuram 22",
  "EXPENSE:Expenses:Vacation:Manali Trip",
  "EXPENSE:Expenses:Vacation:Mysore 2016",
  "EXPENSE:Expenses:Vacation:MYSORE TOUR",
  "EXPENSE:Expenses:Vacation:pollachi 23",
  "EXPENSE:Expenses:Vacation:Pondicherry 2025",
  "EXPENSE:Expenses:Vacation:Pondichery Trip on road",
  "EXPENSE:Expenses:Vacation:sri rangam",
  "EXPENSE:Expenses:Vacation:tirupathi 2021",
  "EXPENSE:Expenses:Vacation:Vizag 2016",
  "EXPENSE:Expenses:Vacation:Vizag 2021",
  "EXPENSE:Expenses:Veera expenses",
  "EQUITY",
  "EQUITY:Equity",
  "EQUITY:Equity:Chits",
  "EQUITY:Equity:Opening Balances",
  "EQUITY:Equity:Share",
  "EQUITY:Equity:Share:Shares",
  "BANK",
  "BANK:Imbalance-INR",
  "BANK:Orphan-INR"
];

// Initial set of basic rules based on provided bank statements
export const INITIAL_RULES: Record<string, string> = {
  // E-Commerce & Tech
  "AMAZON": "EXPENSE:Expenses:5 Amazon Business",
  "AMAZON PAY": "EXPENSE:Expenses:5 Amazon Business",
  "FLIPKART": "EXPENSE:Expenses:1 Material:Electronics",
  "MEESHO": "EXPENSE:Expenses:Lifestyle:Clothes",
  "FREEPIK": "EXPENSE:Expenses:3 Website Business:Website",
  "ADOBE": "EXPENSE:Expenses:1 Material:Software",
  "MICROSOFT": "EXPENSE:Expenses:1 Material:Software",
  "GOOGLE WORKSPACE": "EXPENSE:Expenses:3 Website Business:Website",
  "GODADDY": "EXPENSE:Expenses:3 Website Business:Website",
  "PHONEPE": "ASSET:Assets:Current Assets:Savings Account:Pay Wallets",

  // Food & Dining
  "ZOMATO": "EXPENSE:Expenses:2 Food:Dining",
  "SWIGGY": "EXPENSE:Expenses:2 Food:Takeout/Delivery",
  "EATCLUB": "EXPENSE:Expenses:2 Food:Dining",
  "PARVATHI BAVAN": "EXPENSE:Expenses:2 Food:Snaks",
  "SRI SAI BALAJI": "EXPENSE:Expenses:2 Food:Snaks",
  "KALA G": "EXPENSE:Expenses:2 Food:Dining",
  "HOTEL AADITHYA": "EXPENSE:Expenses:2 Food:Dining",

  // Transport & Travel
  "UBER": "EXPENSE:Expenses:7 Indpendent Consulting:Cabs and Others",
  "OLA": "EXPENSE:Expenses:7 Indpendent Consulting:Cabs and Others",
  "IRCTC": "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Travel expenses",
  "INDIAN RAILWAY": "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Travel expenses",
  "INDIAN OIL": "EXPENSE:Expenses:Auto:Gas",
  "BPCL": "EXPENSE:Expenses:Auto:Gas",
  "HPCL": "EXPENSE:Expenses:Auto:Gas",

  // Business & Services
  "RAZORPAY": "EXPENSE:Expenses:3 Website Business:Ads",
  "FACEBOOK": "EXPENSE:Expenses:3 Website Business:Ads",
  "ADSMA": "EXPENSE:Expenses:3 Website Business:Ads",
  "YOUTUBE": "EXPENSE:Expenses:3 Website Business:Youtube Materials",
  "PENGUN XEROX": "EXPENSE:Expenses:Stationary",
  "SHREE ARUNA": "EXPENSE:Expenses:1 Material:Repair",
  "MOLDTEKPACKAGING": "EQUITY:Equity:Share",

  // Financial & Loans
  "ZERODHA": "EQUITY:Equity:Share",
  "ICCL ZERODHA": "EQUITY:Equity:Share",
  "SBI CARD": "LIABILITY:Liabilities:Credit Card:SBI Credit Card",
  "IDFC": "LIABILITY:Liabilities:Credit Card:IDFC Credit Card",
  "EMI": "LIABILITY:Liabilities:Loans Given",
  "ACH-CR": "LIABILITY:Liabilities:Loans Given",
  "BAJAJ FINANCE": "LIABILITY:Liabilities:Loans Given",

  // Utilities & Bills
  "VODAFONE": "EXPENSE:Expenses:Phone",
  "AIRTEL": "EXPENSE:Expenses:Phone",
  "JIO": "EXPENSE:Expenses:Phone",
  "TNEB": "EXPENSE:Expenses:Utilities:Electric",
  "ACT FIBERNET": "EXPENSE:Expenses:Online Services",
  "ATRIA CONVERGENCE": "EXPENSE:Expenses:Online Services",

  // Medical & Personal
  "UMA EYE CLINIC": "EXPENSE:Expenses:Medical Expenses",
  "PHARMACY": "EXPENSE:Expenses:Medical Expenses",
  "APOLLO": "EXPENSE:Expenses:Medical Expenses",

  // Specific Names found in statements
  "JITHENDRA": "ASSET:Assets:Current Assets:Savings Account",
  "MRJITHEN": "ASSET:Assets:Current Assets:Savings Account",
  "SARANYA": "INCOME:Income:Other Income",
  "TAMILNADU CHAMBER": "EXPENSE:Expenses:3 Website Business:Psy Tam Company:miscellaneous business expense",
  "POLICYBAZAAR": "EXPENSE:Expenses:3 Website Business:Psy Tam Company:Incidentals"
};