export const GNUCASH_ACCOUNTS = [
  "Assets",
  "Assets:Current Assets",
  "Assets:Current Assets:Cash in Hand",
  "Assets:Current Assets:Cash in Hand:Backend",
  "Assets:Current Assets:Cash in Hand:Wallet",
  "Assets:Current Assets:Foriegn Exchange",
  "Assets:Current Assets:Checking Account",
  "Assets:Current Assets:Savings Account",
  "Assets:Current Assets:Savings Account:Andra Bank",
  "Assets:Current Assets:Savings Account:Axis Bank",
  "Assets:Current Assets:Savings Account:HDFC Bank",
  "Assets:Current Assets:Savings Account:Indian Bank",
  "Assets:Current Assets:Savings Account:Pay Wallets",
  "Assets:Current Assets:Savings Account:Pay Wallets:Amazon Pay Balance",
  "Assets:Current Assets:Savings Account:Pay Wallets:Freecharge",
  "Assets:Current Assets:Savings Account:SBI Current Acount",
  "Assets:Current Assets:Savings Account:SBI Joint Account",
  "Assets:Current Assets:Savings Account:IDFC Bank",
  "Assets:Loan",
  "Liabilities",
  "Liabilities:Credit Card",
  "Liabilities:Credit Card:IDFC Credit Card",
  "Liabilities:Credit Card:SBI Credit Card",
  "Liabilities:Aarco",
  "Liabilities:Dad Loan for Business",
  "Liabilities:Loans Given",
  "Liabilities:Others Money",
  "Liabilities:Pending amounts",
  "Liabilities:Phone",
  "Income",
  "Income:Bonus",
  "Income:Cashback",
  "Income:Consulting",
  "Income:Dad money",
  "Income:Dividend",
  "Income:Gambling casino",
  "Income:Gifts Received",
  "Income:Interest Income",
  "Income:Interest Income:Checking Interest",
  "Income:Interest Income:Other Interest",
  "Income:Interest Income:Savings Interest",
  "Income:Other Income",
  "Income:Other Income:Reimbursement",
  "Income:Other Income:Tax reimbursement",
  "Income:Salary",
  "Income:Salary:1 Psychology in Tamil Entity",
  "Income:Salary:1 Psychology in Tamil Entity:Website Business",
  "Income:Salary:Element H",
  "Income:Salary:Foriegn exchange",
  "Income:Salary:Foriegn exchange:Dubai",
  "Income:Salary:Gahan Movie",
  "Income:Salary:Google Payments",
  "Income:Salary:HIMT",
  "Income:Salary:Mcgans Ooty",
  "Income:Salary:Music",
  "Income:Salary:Online Business",
  "Income:Salary:Online Business:Amazon Affiliate",
  "Income:Salary:Online Business:Amazon KDP",
  "Income:Salary:Online Business:Amazon Seller Central",
  "Income:Salary:Online Business:Fiverr Online",
  "Income:Salary:Online Business:Private Consulting",
  "Income:Salary:Online Business:Workshops",
  "Income:Salary:Online Business:Workshops:Assertive Communication",
  "Income:Salary:Online Business:Workshops:Basic Psy oc15 17 Workshop",
  "Income:Salary:Online Business:Workshops:Consolidated Website Earnings",
  "Income:Salary:Online Business:Workshops:digital marketing 2020",
  "Income:Salary:Online Business:Workshops:EQ Workshop",
  "Income:Salary:Online Business:Workshops:Leadership 4 feb 18",
  "Income:Salary:Online Business:Workshops:Leadership Workshop 26 Nov17",
  "Income:Salary:Online Business:Workshops:MBA Workshop",
  "Income:Salary:Online Business:Workshops:money and life management 2021",
  "Income:Salary:Online Business:Workshops:Money manag coim 1012",
  "Income:Salary:Online Business:Workshops:Money Management Jan28 2018",
  "Income:Salary:Online Business:Workshops:Money Management Workshop 5 no 17",
  "Income:Salary:Online Business:Workshops:Pre Marital 2018",
  "Income:Salary:Online Business:Workshops:SIS Dubey",
  "Income:Salary:Online Business:Workshops:TDP Jan 567 2018",
  "Income:Salary:Online Business:Youtube",
  "Income:Salary:Other Education",
  "Income:Salary:Pearl",
  "Income:Salary:Scale Up Training",
  "Income:Salary:St Thomas",
  "Income:Salary:Sun TV",
  "Income:Salary:Web Development",
  "Income:Salary:Win or Win",
  "Income:Salary:YES Chamber of commerce",
  "Income:Selling Stuff",
  "Expenses",
  "Expenses:1 Material",
  "Expenses:1 Material:Prec Metals",
  "Expenses:1 Material:Repair",
  "Expenses:1 Material:Software",
  "Expenses:1 Material:Books",
  "Expenses:1 Material:Computer",
  "Expenses:1 Material:Electronics",
  "Expenses:1 Material:Equipment",
  "Expenses:2 Food",
  "Expenses:2 Food:Dining",
  "Expenses:2 Food:Snaks",
  "Expenses:2 Food:Takeout/Delivery",
  "Expenses:3 Website Business",
  "Expenses:3 Website Business:AARCO Joint Venture",
  "Expenses:3 Website Business:Ads",
  "Expenses:3 Website Business:Education Activities",
  "Expenses:3 Website Business:Psy Tam Company",
  "Expenses:3 Website Business:Psy Tam Company:Bills",
  "Expenses:3 Website Business:Psy Tam Company:Equipement",
  "Expenses:3 Website Business:Psy Tam Company:Hotels Rooms",
  "Expenses:3 Website Business:Psy Tam Company:Incidentals",
  "Expenses:3 Website Business:Psy Tam Company:Interest for Loan",
  "Expenses:3 Website Business:Psy Tam Company:miscellaneous business expense",
  "Expenses:3 Website Business:Psy Tam Company:Salary",
  "Expenses:3 Website Business:Psy Tam Company:sundry salary",
  "Expenses:3 Website Business:Psy Tam Company:Travel expenses",
  "Expenses:3 Website Business:Psy Tam Company:Website",
  "Expenses:3 Website Business:Psyasap",
  "Expenses:3 Website Business:Psychologyintamil",
  "Expenses:3 Website Business:Salary for Works",
  "Expenses:3 Website Business:V S Jithendra Personal Site",
  "Expenses:3 Website Business:Workshops",
  "Expenses:3 Website Business:Workshops:2022 April Workshop",
  "Expenses:3 Website Business:Workshops:2022 May Workshop",
  "Expenses:3 Website Business:Workshops:Assertive Com Workshop",
  "Expenses:3 Website Business:Workshops:Basic Psy oc 17 Workshop",
  "Expenses:3 Website Business:Workshops:Business Strategy Workshop Aug2018",
  "Expenses:3 Website Business:Workshops:critical thinking 2022",
  "Expenses:3 Website Business:Workshops:digital maketing 2020",
  "Expenses:3 Website Business:Workshops:EQ Workshop",
  "Expenses:3 Website Business:Workshops:Leadership 26 Nov",
  "Expenses:3 Website Business:Workshops:Leadership 4 feb 18",
  "Expenses:3 Website Business:Workshops:Leadership fr SMall Business Trichy",
  "Expenses:3 Website Business:Workshops:MBA Workshop 2025",
  "Expenses:3 Website Business:Workshops:MM3 Jan 28 18",
  "Expenses:3 Website Business:Workshops:money and life management 2021",
  "Expenses:3 Website Business:Workshops:Money Management Dec10",
  "Expenses:3 Website Business:Workshops:Money Management No 17",
  "Expenses:3 Website Business:Workshops:Pre Marital Workshop 2018",
  "Expenses:3 Website Business:Workshops:Relationship 24",
  "Expenses:3 Website Business:Workshops:SIS Feb 28",
  "Expenses:3 Website Business:Workshops:Trainer Development",
  "Expenses:3 Website Business:Workshops:Workshops Consolidated 2019",
  "Expenses:3 Website Business:Youtube Materials",
  "Expenses:4 Music Business Expenses",
  "Expenses:4 Music Business Expenses:Ads",
  "Expenses:4 Music Business Expenses:Education",
  "Expenses:4 Music Business Expenses:Gahan Music Expenses",
  "Expenses:4 Music Business Expenses:INstrument and Others",
  "Expenses:4 Music Business Expenses:own compose songs",
  "Expenses:4 Music Business Expenses:Software",
  "Expenses:4 Music Business Expenses:Video Shoot Expenses",
  "Expenses:5 Amazon Business",
  "Expenses:5 Amazon Business:Books",
  "Expenses:5 Amazon Business:Equipments",
  "Expenses:5 Amazon Business:Other Tools",
  "Expenses:5 Amazon Business:Stationary",
  "Expenses:6 Foriegn Expenses",
  "Expenses:6 Foriegn Expenses:Dubai",
  "Expenses:7 Indpendent Consulting",
  "Expenses:7 Indpendent Consulting:Cabs and Others",
  "Expenses:7 Indpendent Consulting:Food",
  "Expenses:7 Indpendent Consulting:Tickets for Travels",
  "Expenses:Adjustment",
  "Expenses:Advertisement",
  "Expenses:Auto",
  "Expenses:Auto:Bus",
  "Expenses:Auto:Cab",
  "Expenses:Auto:Car",
  "Expenses:Auto:Fees",
  "Expenses:Auto:Gas",
  "Expenses:Auto:Parking",
  "Expenses:Auto:Repair and Maintenance",
  "Expenses:Bank Service Charge",
  "Expenses:Domestic",
  "Expenses:Domestic :apartment maintenance",
  "Expenses:Domestic :Appliances",
  "Expenses:Domestic :Borewell",
  "Expenses:Domestic :House expense",
  "Expenses:Domestic :Household Items",
  "Expenses:Domestic :Maintanance",
  "Expenses:Durga Marriage",
  "Expenses:Education",
  "Expenses:Education:Books",
  "Expenses:Education:Fees",
  "Expenses:Education:Online Courses",
  "Expenses:Education:PHD",
  "Expenses:Entertainment",
  "Expenses:Entertainment:Games",
  "Expenses:Entertainment:Music/Movies",
  "Expenses:Entertainment:Recreation",
  "Expenses:Entertainment:Subscription",
  "Expenses:Entertainment:Travel",
  "Expenses:Fine",
  "Expenses:Gifts",
  "Expenses:Govt",
  "Expenses:Groceries",
  "Expenses:Hobbies",
  "Expenses:Insurance",
  "Expenses:Insurance:Auto Insurance",
  "Expenses:Insurance:Health Insurance",
  "Expenses:Insurance:Life Insurance",
  "Expenses:Laundry/Dry Cleaning",
  "Expenses:Lifestyle",
  "Expenses:Lifestyle:Clothes",
  "Expenses:Lifestyle:Other",
  "Expenses:Marriage",
  "Expenses:Medical Expenses",
  "Expenses:Miscellaneous",
  "Expenses:office",
  "Expenses:Online Services",
  "Expenses:Phone",
  "Expenses:Public Transportation",
  "Expenses:Rent",
  "Expenses:Salary",
  "Expenses:Spent for Others in Debt",
  "Expenses:Stationary",
  "Expenses:Subscriptions",
  "Expenses:Subscriptions:Other Media",
  "Expenses:Subscriptions:SBI Credit Card",
  "Expenses:Supplies",
  "Expenses:Taxes",
  "Expenses:Taxes:Auditor Fees",
  "Expenses:Taxes:Federal",
  "Expenses:Taxes:income Tax",
  "Expenses:Taxes:Medicare",
  "Expenses:Taxes:Other Tax",
  "Expenses:Taxes:Social Security",
  "Expenses:Taxes:State/Province",
  "Expenses:Utilities",
  "Expenses:Utilities:Electric",
  "Expenses:Utilities:Garbage collection",
  "Expenses:Utilities:Gas",
  "Expenses:Utilities:Water",
  "Expenses:Vacation",
  "Expenses:Vacation:andaman 2019",
  "Expenses:Vacation:Banglore",
  "Expenses:Vacation:Banglore 2017",
  "Expenses:Vacation:banglore 2019",
  "Expenses:Vacation:bombay",
  "Expenses:Vacation:China 2025",
  "Expenses:Vacation:Coimbatore Nov2017",
  "Expenses:Vacation:Coonor jEYKAR WEDDING",
  "Expenses:Vacation:Coorg 2017 Dec",
  "Expenses:Vacation:Coorg 2022",
  "Expenses:Vacation:Coorg with Jey friends",
  "Expenses:Vacation:delhi manali 2019-20",
  "Expenses:Vacation:Dubai 2022",
  "Expenses:Vacation:Goa 2017",
  "Expenses:Vacation:Goa 2018",
  "Expenses:Vacation:Goa 2019 July",
  "Expenses:Vacation:Goa 2019 March",
  "Expenses:Vacation:Goa 2021",
  "Expenses:Vacation:Goa 2022",
  "Expenses:Vacation:Goa 2024",
  "Expenses:Vacation:Goa may 2021",
  "Expenses:Vacation:GOA TRIP",
  "Expenses:Vacation:Goa Trip 2016 May",
  "Expenses:Vacation:Honeymoon",
  "Expenses:Vacation:Jeshu wedding",
  "Expenses:Vacation:Kanyakumari Trip",
  "Expenses:Vacation:Kishore wedding",
  "Expenses:Vacation:Leh 23",
  "Expenses:Vacation:Mahabalipuram 22",
  "Expenses:Vacation:Manali Trip",
  "Expenses:Vacation:Mysore 2016",
  "Expenses:Vacation:MYSORE TOUR",
  "Expenses:Vacation:pollachi 23",
  "Expenses:Vacation:Pondicherry 2025",
  "Expenses:Vacation:Pondichery Trip on road",
  "Expenses:Vacation:sri rangam",
  "Expenses:Vacation:tirupathi 2021",
  "Expenses:Vacation:Vizag 2016",
  "Expenses:Vacation:Vizag 2021",
  "Expenses:Veera expenses",
  "Equity",
  "Equity:Chits",
  "Equity:Opening Balances",
  "Equity:Share",
  "Equity:Share:Shares",
  "Imbalance-INR",
  "Orphan-INR"
];

// Initial set of basic rules
export const INITIAL_RULES: Record<string, string> = {
  "AMAZON": "Expenses:5 Amazon Business",
  "ZOMATO": "Expenses:2 Food:Dining",
  "SWIGGY": "Expenses:2 Food:Takeout/Delivery",
  "RAZORPAY": "Expenses:3 Website Business:Ads",
  "FACEBOOK": "Expenses:3 Website Business:Ads",
  "SBI CARD": "Liabilities:Credit Card:SBI Credit Card",
  "IDFC": "Liabilities:Credit Card:IDFC Credit Card",
  "POLICYBAZAAR": "Expenses:3 Website Business:Psy Tam Company:Incidentals",
  "IRCTC": "Expenses:3 Website Business:Psy Tam Company:Travel expenses"
};